# Generated by Django 5.0.3 on 2024-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_personal_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_token_secret',
            field=models.CharField(default='5015f315-37d0-4f3f-8492-07ae95e268b7', max_length=36),
        ),
    ]
