# Generated by Django 5.0.3 on 2024-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_personal_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_token_secret',
            field=models.CharField(default='61904daa-b36b-43dc-8395-f7345878c963', max_length=36),
        ),
    ]
