# Generated by Django 5.0.3 on 2024-05-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_personal_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_token_secret',
            field=models.CharField(default='93ba6138-437f-49a9-a07d-95f7469689d8', max_length=36),
        ),
    ]
