# Generated by Django 5.0.3 on 2024-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_personal_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_token_secret',
            field=models.CharField(default='ab4d48a6-71cb-43f2-b1ba-a71c990a4726', max_length=36),
        ),
    ]
