# Generated by Django 5.0.4 on 2024-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_personal_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_token_secret',
            field=models.CharField(default='67c5ec07-af14-45b6-a5d3-4b1209ff6586', max_length=36),
        ),
    ]
