# Generated by Django 5.0.3 on 2024-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
