# Generated by Django 5.0.3 on 2024-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplace',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='dayplace',
            name='time_start',
        ),
        migrations.AddField(
            model_name='dayplace',
            name='name',
            field=models.CharField(default='aa', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayplace',
            name='sort_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayplace',
            name='visited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
