# Generated by Django 5.0.4 on 2024-05-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_dayplace_time_end_remove_dayplace_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplace',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.trip'),
        ),
    ]
